# Generated by Django 4.0.6 on 2022-07-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.IntegerField()),
                ('direccion', models.CharField(max_length=20)),
                ('num_telf', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('num_env', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('tipo_env', models.IntegerField(choices=[[0, 'domicilio'], [1, 'retiro'], [2, 'express']])),
                ('destinatario', models.CharField(max_length=20)),
                ('rut_dest', models.IntegerField()),
                ('contacto_dest', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[[0, 'Recibido'], [1, 'Traslado'], [2, 'Reparto'], [3, 'Entregado'], [4, 'Sin Informacion']])),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.encomienda')),
            ],
        ),
    ]
